export const cookie = [
  {
    domain: ".olimerca.com",
    expirationDate: 1616701987,
    hostOnly: false,
    httpOnly: false,
    name: "_ga",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    session: false,
    storeId: "0",
    value: "GA1.2.1571680843.1553522287",
    id: 1
  },
  {
    domain: ".olimerca.com",
    expirationDate: 1553630036,
    hostOnly: false,
    httpOnly: false,
    name: "_gali",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    session: false,
    storeId: "0",
    value: "ctl00_MainContent_ctrlTablaPreciosAceite13_LinkButton1",
    id: 2
  },
  {
    domain: ".olimerca.com",
    expirationDate: 1553630047,
    hostOnly: false,
    httpOnly: false,
    name: "_gat",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    session: false,
    storeId: "0",
    value: "1",
    id: 3
  },
  {
    domain: ".olimerca.com",
    expirationDate: 1553716387,
    hostOnly: false,
    httpOnly: false,
    name: "_gid",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    session: false,
    storeId: "0",
    value: "GA1.2.2016685428.1553522287",
    id: 4
  },
  {
    domain: "www.olimerca.com",
    hostOnly: true,
    httpOnly: true,
    name: "ASP.NET_SessionId",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    session: true,
    storeId: "0",
    value: "xpdnil3ocrcu22db0jwntb3g",
    id: 5
  },
  {
    domain: "www.olimerca.com",
    expirationDate: 1616594288,
    hostOnly: true,
    httpOnly: false,
    name: "cookiesAllowed",
    path: "/precios/tipoInforme",
    sameSite: "no_restriction",
    secure: false,
    session: false,
    storeId: "0",
    value: "1",
    id: 6
  },
  {
    domain: "www.olimerca.com",
    hostOnly: true,
    httpOnly: false,
    name: "gsScrollPos-204",
    path: "/precios/tipoInforme",
    sameSite: "no_restriction",
    secure: false,
    session: true,
    storeId: "0",
    value: "",
    id: 7
  },
  {
    domain: "www.olimerca.com",
    hostOnly: true,
    httpOnly: false,
    name: "gsScrollPos-231",
    path: "/precios/tipoInforme",
    sameSite: "no_restriction",
    secure: false,
    session: true,
    storeId: "0",
    value: "0",
    id: 8
  },
  {
    domain: "www.olimerca.com",
    expirationDate: 1553716400,
    hostOnly: true,
    httpOnly: false,
    name: "hideNewsletter",
    path: "/precios/tipoInforme",
    sameSite: "no_restriction",
    secure: false,
    session: false,
    storeId: "0",
    value: "1",
    id: 9
  }
];
